# Generated by Django 5.2.4 on 2025-07-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
