# Generated by Django 5.2.4 on 2025-07-31 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_edital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='campus',
        ),
        migrations.AlterField(
            model_name='edital',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='edital',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='edital',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.campus'),
        ),
    ]
