# Generated by Django 5.2.4 on 2025-08-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_remove_edital_campus_alter_edital_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='campus',
        ),
        migrations.AddField(
            model_name='edital',
            name='campus',
            field=models.ManyToManyField(blank=True, to='cadastro.campus'),
        ),
    ]
