# Generated by Django 5.2.4 on 2025-08-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='data_final_analise',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edital',
            name='data_final_recurso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edital',
            name='data_recurso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
