# Generated by Django 5.2.4 on 2025-08-05 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_edital_data_final_analise_edital_data_final_recurso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='cadastro.edital')),
            ],
        ),
    ]
