# Generated by Django 5.2.4 on 2025-08-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_grupoatendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='equipe',
            field=models.ManyToManyField(related_name='editais', to='cadastro.usuario'),
        ),
        migrations.AddField(
            model_name='edital',
            name='grupos_trabalho',
            field=models.ManyToManyField(related_name='editais', to='cadastro.grupotrabalho'),
        ),
    ]
