# Generated by Django 5.2.4 on 2025-08-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_edital_equipe_edital_grupos_trabalho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='data_final_analise',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='data_final_recurso',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='data_recurso',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='grupos_trabalho',
        ),
    ]
