# Generated by Django 5.2.4 on 2025-08-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_remove_edital_data_final_analise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='numero',
            field=models.TextField(max_length=50),
        ),
    ]
