# Generated by Django 5.2.4 on 2025-08-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_alter_edital_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='avaliadores_historico',
            field=models.ManyToManyField(blank=True, related_name='editais_historico', to='cadastro.usuario'),
        ),
        migrations.AddField(
            model_name='edital',
            name='avaliadores_renda',
            field=models.ManyToManyField(blank=True, related_name='editais_renda', to='cadastro.usuario'),
        ),
    ]
