# Generated by Django 5.2.4 on 2025-08-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_edital_avaliadores_historico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='data_final_analise_historico',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edital',
            name='data_final_analise_renda',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edital',
            name='data_final_recurso_historico',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edital',
            name='data_final_recurso_renda',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edital',
            name='data_inicial_analise_historico',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edital',
            name='data_inicial_analise_renda',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edital',
            name='data_recurso_historico',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edital',
            name='data_recurso_renda',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edital',
            name='grupos_atendimento',
            field=models.ManyToManyField(blank=True, related_name='editais', to='cadastro.grupoatendimento'),
        ),
    ]
