# Generated by Django 5.2.4 on 2025-08-06 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_edital_data_final_analise_historico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='grupos_atendimento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='grupos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='grupos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.grupotrabalho'),
        ),
    ]
