# Generated by Django 5.2.4 on 2025-08-06 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_remove_edital_grupos_atendimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='grupos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.grupotrabalho'),
        ),
    ]
