# Generated by Django 5.2.4 on 2025-08-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_alter_usuario_grupos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='grupos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='grupos',
            field=models.ManyToManyField(blank=True, null=True, to='cadastro.grupotrabalho'),
        ),
    ]
