# Generated by Django 5.2.4 on 2025-08-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0018_edital_ativo_edital_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='observacoes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='observacoes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
