# Generated by Django 5.2.4 on 2025-08-14 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0019_alter_edital_observacoes_alter_usuario_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('analise', 'Análise'), ('recurso', 'Recurso')], max_length=20)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.usuario')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.edital')),
            ],
        ),
    ]
