# Generated by Django 5.2.4 on 2025-11-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0020_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='ano',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
