# Generated by Django 5.2.4 on 2025-11-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0022_alter_usuario_agencia_alter_usuario_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='valor_unitario_avaliacao',
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='edital',
            name='valor_unitario_renda',
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
