# Generated by Django 5.2.4 on 2025-11-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0023_edital_valor_unitario_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
